---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
objects:
- kind: CronJob
  apiVersion: batch/v1
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
  spec:
    schedule: ${SCHEDULE}
    concurrencyPolicy: Forbid
    jobTemplate:
      metadata:
        labels:
          app: ${NAME}
      spec:
        backoffLimit: ${{BACKOFF_LIMIT}}
        activeDeadlineSeconds: ${{ACTIVE_DEADLINE_SECONDS}}
        template:
          metadata:
            labels:
              app: ${NAME}
          spec:
            restartPolicy: OnFailure
            volumes:
            - name: temp-volume
              emptyDir: {}
            - name: postgres-diag-queries-configmap
              configMap:
                name: ${QUERIES_CONFIGMAP}
            containers:
              - name: mysql-diag
                image: "${IMAGE}:${IMAGE_TAG}"
                imagePullPolicy: ${IMAGE_PULL_POLICY}
                volumeMounts:
                - name: temp-volume
                  mountPath: /temp-dir
                - name: postgres-diag-queries-configmap
                  mountPath: /postgres-diag-queries
                  readOnly: true
                env:
                - name: TEMP_DIR
                  value: /temp-dir
                - name: TAR_FILE_HEADER
                  value: ${NAME}
                - name: SET_X
                  value: "${SET_X}"
                - name: PGHOST
                  valueFrom:
                    secretKeyRef:
                      name: ${POSTGRES_DB_SECRET_NAME}
                      key: "db.host"
                - name: PGPORT
                  valueFrom:
                    secretKeyRef:
                      name: ${POSTGRES_DB_SECRET_NAME}
                      key: "db.port"
                      optional: true
                - name: PGDATABASE
                  valueFrom:
                    secretKeyRef:
                      name: ${POSTGRES_DB_SECRET_NAME}
                      key: "db.name"
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: ${POSTGRES_DB_SECRET_NAME}
                      key: "db.user"
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${POSTGRES_DB_SECRET_NAME}
                      key: "db.password"
                      optional: true
                - name: S3_BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      key: bucket
                      name: ${AWS_S3_SECRET_NAME}
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      key: aws_access_key_id
                      name: ${AWS_S3_SECRET_NAME}
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      key: aws_secret_access_key
                      name: ${AWS_S3_SECRET_NAME}
                - name: AWS_DEFAULT_REGION
                  valueFrom:
                    secretKeyRef:
                      key: aws_region
                      name: ${AWS_S3_SECRET_NAME}
                resources:
                  limits:
                    cpu: ${CPU_LIMIT}
                    memory: ${MEMORY_LIMIT}
                  requests:
                    cpu: ${CPU_REQUEST}
                    memory: ${MEMORY_REQUEST}

parameters:
- name: NAME
  value: "postgres-diag-queries"
- name: IMAGE
  value: "quay.io/redhat-services-prod/app-sre-tenant/postgres-diag-queries-main/postgres-diag-queries-main"
- name: IMAGE_TAG
  value: "latest"
- name: IMAGE_PULL_POLICY
  value: "Always"
- name: SCHEDULE
  value: "* * * * *"
- name: AWS_S3_SECRET_NAME
  value: "postgres-diag-queries-s3"
- name: POSTGRES_DB_SECRET_NAME
  value: "postgres-diag-queries-rds"
- name: BACKOFF_LIMIT
  value: "5"
- name: ACTIVE_DEADLINE_SECONDS
  value: "1200"
- name: CPU_REQUEST
  value: "100m"
  required: true
- name: MEMORY_REQUEST
  value: "128Mi"
  required: true
- name: MEMORY_LIMIT
  value: "1Gi"
  required: true
- name: CPU_LIMIT
  value: "1000m"
- name: QUERIES_CONFIGMAP
  value: "postgres-diag-queries"
- name: SET_X
  value: "false"
